### ISSUE TITLE
А нужен ли form-field?

### ISSUE THREAD

**Issue by belozer** [yar-usenko/bem-forms#1]
В bem-core@v4 JS можно писать для элементов.

**Comment by yar-usenko** [comment]
Я вот тоже об этом думаю.
На выходных посмотрю на свои формы и, скорей всего, сделаю элементом

**Comment by yar-usenko** [comment]
А fieldsed? Либо его тоже делать элементом,  либо form-field оставлять элементом, либо каждый раз при вкладывании писать в bemjson { block: 'form', elem: 'field' }

**Comment by belozer** [comment]
Думаю элементом. Для чего нужно использовать вне контекста формы?

**Comment by yar-usenko** [comment]
Тогда решено - все в элементы. Хоть их и много получиться

**Comment by yar-usenko** [comment]
#2 #3
